varnish:
  - name: "LocalVarnish"
    host: "localhost"
    port: 6085
    scheme: "http"
    username: "admin"
    # Provide either password or passwordEncrypted and encryptionKey
    password: "admin"
    passwordEncrypted: ""
    encryptionKey: ""
    enabledMetricsPath: "monitors/VarnishMonitor/EnabledMetrics.xml"
    proxyConfig:
      uri:
      username:
      password:
  - name: "RemoteVarnish"
    host: "localhost"
    port: 6085
    scheme: "http"
    username: "admin"
    password: "admin"
    passwordEncrypted: ""
    encryptionKey: ""
    enabledMetricsPath: "monitors/VarnishMonitor/EnabledMetrics.xml"
    proxyConfig:
      uri:
      username:
      password:

# Number of concurrent threads for
# dealing with multiple Varnish instances
# Note: You don't necessarily have to match the no of threads
# to the no of Varnish instances configured above
# unless you have a lot of CPUs in your machine
numberOfVarnishThreads: 2


#This will create this metric in all the tiers, under this path
#metricPrefix: "Custom Metrics|Varnish|"

#This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
metricPrefix: Server|Component:<COMPONENT_ID>|Custom Metrics|Varnish